### PR TITLE
Fixes Symbols as you type for 2.1.41, breaks backwards compatibility

### PR DESCRIPTION
**Pull request by hgiesel**
Backwards compatibility should not be required, as Anki allows for uploading different add-on versions per Anki version.

I've also created a bin directory for containing development scripts. I've also added a `link` script, for symlinking the repo into Anki (so you don't have to move it there)

Comissioned by @AnkingMed

### CODE REVIEW

**Comment by AnKingMed** [comment]
@jefdongus  I tested this and it works

**Comment by AnKingMed** [comment]
@jefdongus turns out that there is a small issue in the browser. I'll have @hgiesel work on that.  Are you available to merge the pull request and put it on Ankiweb anytime soon? If not we can make a separate version of the add-on

**Comment by jefdongus** [comment]
Ooh, looks like 2.1.41 was a pretty big update, which is both 😄 and 😦. Thanks so much @hgiesel and @AnKingMed! I will look into this a bit more in the next few days, but for the browser 1) to get it not to crash the `on_browser_init()` signature just needs to get updated (or preferably get updated to use a hook), but 2) `get_search_box()` is returning `None` -- this has been an issue intermittently in the past and I'm not sure why, since it should run at the end of `Browser.init()`...

The JS looks great though!

**Comment by jefdongus** [comment]
I made a small edit to restore backwards compatibility (will commit those changes after merging this PR) -- the addon will load the old replacer.js for Anki version <= 2.1.40 and this new version for >= 2.1.41. Can't get the symbol stuff in the browser to work just yet but at least it won't crash for now.

**Pull request merged**
